### ISSUE TITLE
Not loading and error in Home Assistant 2022.9.3

### ISSUE THREAD

**Issue by McGiverGim** [Limych/ha-jq300#117]
**Environment**

- Home Assistant Core release with the issue: 2022.9.3
- This custom component release with the issue: 0.10.5
- Last working this custom component release (if known): Not sure
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant

**Describe the bug**

Home Assistant does not load the integration/sensors. Looking at the logs I can see this error:
```text
2022-09-14 10:15:58.695 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up jq300 platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/jq300/binary_sensor.py", line 40, in async_setup_entry
    await account.async_update_sensors_or_timeout()
  File "/config/custom_components/jq300/api.py", line 573, in async_update_sensors_or_timeout
    await self.async_update_sensors()
  File "/config/custom_components/jq300/api.py", line 566, in async_update_sensors
    self._extract_sensors_data(device_id, ts_now, ret["deviceValueVos"])
  File "/config/custom_components/jq300/api.py", line 465, in _extract_sensors_data
    res[sensor_id] = float(sensor["content"])
ValueError: could not convert string to float: ''
```
It seems the value of some sensor is not a float anymore. I don't know if it is a problem of Home Assistant or something changed in the cloud. The debug log seems to me some problem connecting with the cloud?

**Configuration.yaml**
```yaml
None
```

**Steps to Reproduce**

Install latest version of Home Assistant. I'm not sure if it matters or is a cloud problem

**Expected behavior**

Have a working integration with sensors.

**Debug log**

```text
2022-09-14 10:30:44.533 INFO (MainThread) [homeassistant.setup] Setting up jq300
2022-09-14 10:30:44.533 INFO (MainThread) [custom_components.jq300] 
-------------------------------------------------------------------
JQ-300/200/100 Indoor Air Quality Meter
Version: 0.10.5
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-jq300/issues
-------------------------------------------------------------------
2022-09-14 10:30:44.533 INFO (MainThread) [homeassistant.setup] Setup of domain jq300 took 0.0 seconds
2022-09-14 10:30:45.269 DEBUG (MainThread) [custom_components.jq300] Connecting to account mi***l@gm**l.com
2022-09-14 10:30:45.269 DEBUG (MainThread) [custom_components.jq300.api] Connecting to cloud server
2022-09-14 10:30:45.269 DEBUG (MainThread) [custom_components.jq300.api] Requesting URL http://www.youpinyuntai.com:32086/ypyt-api/api/app/loginByEmail
2022-09-14 10:30:48.565 DEBUG (MainThread) [custom_components.jq300.api] _query ret 200
2022-09-14 10:30:48.567 DEBUG (MainThread) [custom_components.jq300.api] Start connecting to cloud MQTT-server
2022-09-14 10:30:48.571 DEBUG (MainThread) [custom_components.jq300.api] Updating devices list for account mi***l@gm**l.com
2022-09-14 10:30:48.572 DEBUG (MainThread) [custom_components.jq300.api] Requesting URL http://www.youpinyuntai.com:32086/ypyt-api/api/app/deviceManager
2022-09-14 10:30:48.865 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'***'
2022-09-14 10:30:48.999 DEBUG (MainThread) [custom_components.jq300.api] _query ret 200
2022-09-14 10:30:49.000 DEBUG (MainThread) [custom_components.jq300.api] Subscribe for new MQTT topics: ***
2022-09-14 10:30:49.026 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.jq300
2022-09-14 10:30:49.031 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.jq300
2022-09-14 10:30:49.034 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Setup binary sensors for account mi***l@gm**l.com
2022-09-14 10:30:49.034 DEBUG (MainThread) [custom_components.jq300.api] Updating sensors state for account mi***l@gm**l.com
2022-09-14 10:30:49.034 DEBUG (MainThread) [custom_components.jq300.api] Requesting URL https://www.youpinyuntai.com:31447/device/list
2022-09-14 10:30:49.038 DEBUG (MainThread) [custom_components.jq300.sensor] Setup sensors for account mi***l@gm**l.com
2022-09-14 10:30:49.039 DEBUG (MainThread) [custom_components.jq300.api] Finished fetching mi***l@gm**l.com device's sensors in 0.000 seconds
2022-09-14 10:30:49.039 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:30:49.192 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Received CONNACK (0, 0)
2022-09-14 10:30:49.192 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Connected to MQTT
2022-09-14 10:30:49.192 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Sending SUBSCRIBE (d0, m1) [(b'***', 0)]
2022-09-14 10:30:49.492 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Received SUBACK
2022-09-14 10:30:57.043 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:30:57.045 ERROR (MainThread) [custom_components.jq300.api] Error! 
2022-09-14 10:30:57.054 DEBUG (MainThread) [custom_components.jq300.api] Finished fetching mi***l@gm**l.com device's sensors in 8.020 seconds
2022-09-14 10:30:57.054 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:30:59.190 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform jq300 is taking over 10 seconds.
2022-09-14 10:30:59.192 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform jq300 is taking over 10 seconds.
2022-09-14 10:31:00.145 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:00.145 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:03.195 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:03.195 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:06.413 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:06.413 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:09.416 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:09.416 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:12.426 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:12.427 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:15.429 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:15.429 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:18.431 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:18.432 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:21.433 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:21.436 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:24.435 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:24.438 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:27.436 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:27.441 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:30.438 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:30.442 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:33.441 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:33.446 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:36.442 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:36.448 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:39.444 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:39.450 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:41.872 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: binary_sensor.jq300, sensor.jq300
2022-09-14 10:31:42.446 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:42.451 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:45.448 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:45.454 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:48.451 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:48.455 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:49.029 ERROR (MainThread) [homeassistant.components.binary_sensor] Setup of platform jq300 is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-09-14 10:31:49.034 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform jq300 is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-09-14 10:31:49.289 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Sending PINGREQ
2022-09-14 10:31:49.584 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Received PINGRESP
2022-09-14 10:31:53.629 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:53.629 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:56.776 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:56.777 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:59.779 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:31:59.779 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:02.783 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:02.784 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:05.786 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:05.787 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:08.788 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:08.789 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:11.790 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:11.791 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:14.797 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:14.798 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:17.799 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:17.799 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:20.800 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:20.801 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:24.062 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:24.062 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:27.063 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:27.064 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:30.066 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:30.067 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:33.068 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:33.069 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:36.070 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:36.071 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:39.072 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:39.073 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:42.074 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:42.075 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:45.076 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:45.077 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:48.078 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:48.079 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:50.221 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Sending PINGREQ
2022-09-14 10:32:50.508 DEBUG (Thread-3 (_thread_main)) [custom_components.jq300.api] Received PINGRESP
2022-09-14 10:32:51.081 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:51.081 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:54.083 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:54.083 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:57.085 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:32:57.085 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:33:00.086 DEBUG (MainThread) [custom_components.jq300.sensor] Sensors list is not ready. Wait for 3 sec...
2022-09-14 10:33:00.091 DEBUG (MainThread) [custom_components.jq300.binary_sensor] Sensors list is not ready. Wait for 3 sec...

```

**Additional context**

The strange thing is that the debug logs does not show the same error than when the debug log is disabled.

**Comment by rogodra** [comment]
I have the same problem.

**Comment by McGiverGim** [comment]
It seems it is working again right now for me. I don't know what is the change, I updated Home Assistant OS to the latest version, released today. I don't know if it matters or simply the cloud has started to work again. I close this.
