### ISSUE TITLE
Error in logs when starting Home Assistant

### ISSUE THREAD

**Issue by McGiverGim** [Limych/ha-jq300#48]
**Environment**

- Home Assistant Core release with the issue: 2021.6.0 (this happened too in early versions)
- This custom component release with the issue: 0.9.1
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant

**Describe the bug**

The integration works without problem, but I have this error in logs when I start Home Assistant:
```text
2021-06-03 09:01:24 ERROR (MainThread) [custom_components.jq300.api] Error! 
```

**Configuration.yaml**

Using UI

**Steps to Reproduce**

In my case:
1. Restart Home Assistant.
2. Look at the logs.

**Expected behavior**

No errors in the log.

**Debug log**

```text
2021-06-03 09:27:22 DEBUG (MainThread) [custom_components.jq300] Connecting to account [XXXXXX]
2021-06-03 09:27:22 DEBUG (MainThread) [custom_components.jq300.api] Connecting to cloud server
2021-06-03 09:27:22 DEBUG (MainThread) [custom_components.jq300.api] Requesting URL http://www.youpinyuntai.com:32086/ypyt-api/api/app/loginByEmail
2021-06-03 09:27:34 ERROR (MainThread) [custom_components.jq300.api] Error! 
2021-06-03 09:27:34 DEBUG (MainThread) [custom_components.jq300.api] Connecting to cloud server (FORCE mode)
2021-06-03 09:27:34 DEBUG (MainThread) [custom_components.jq300.api] Requesting URL http://www.youpinyuntai.com:32086/ypyt-api/api/app/loginByEmail
```

**Additional context**

None.

**Comment by gitothy** [comment]
Also having the same issue.  Looks like they've blocked access to their cloud platform again?

```
2021-07-11 00:12:28 ERROR (MainThread) [custom_components.jq300.api] Error! [Errno 104] Connection reset by peer
2021-07-11 00:12:28 ERROR (MainThread) [custom_components.jq300.api] Can't connect to cloud.
2021-07-11 00:12:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry configuration.yaml for jq300
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/jq300/__init__.py", line 107, in async_setup_entry
for device_id in devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by gitothy** [comment]
@McGiverGim FYI you might want to check this again as it now seems to have resolved itself on my instance.  I didn't change any config or take any specific action.  Have restarted HA a few times including updating to the latest 2021.7.3... and suddenly data's flowing back in [I don't think 2021.7.3 is the fix].

I have only used the official _Perthings_ app once at initial setup.  My current thinking is that iOS periodically wakes the app in the background and that might trigger a re-authentication which in turn unblocks this integration.  If you haven't tried it then go in to the app and check if data is being logged, if so then restart HA and see if it's back working.

**Comment by Limych** [comment]
Is this error still actual now?

**Comment by McGiverGim** [comment]
I think remember it appears with latest version but I'm out of home. I will check it next week.

**Comment by McGiverGim** [comment]
It seems it continues, I don't know the reason. This is from today:
```
Este error se originó a partir de una integración personalizada.

Logger: custom_components.jq300.api
Source: custom_components/jq300/api.py:213
Integration: JQ-300/200/100 Indoor Air Quality Meter (documentation, issues)
First occurred: 8:56:59 (1 occurrences)
Last logged: 8:56:59

Error!

```

**Comment by areyoufserious** [comment]
Still actual

**Comment by McGiverGim** [comment]
This error seems fixed and I don't see it in my logs with latest version. I close the issue.

**Comment by McGiverGim** [comment]
I reopen the issue :(, I've seen the error again, version 2022.8.0 of Home Assistant:
```
Este error se originó a partir de una integración personalizada.

Logger: custom_components.jq300.api
Source: custom_components/jq300/api.py:553
Integration: JQ-300/200/100 Indoor Air Quality Meter (documentation, issues)
First occurred: 16:35:43 (1 occurrences)
Last logged: 16:35:43

Error!
```

**Comment by McGiverGim** [comment]
More infor, with more log information. But is the same @gitothy published before:
```
2022-08-08 08:05:49.890 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Calidad del aire for jq300
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/jq300/__init__.py", line 107, in async_setup_entry
for device_id in devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by McGiverGim** [comment]
It seems to point to the list of devices:
https://github.com/Limych/ha-jq300/blob/700110e4a84be4392b824dd932b82b5894a42491/custom_components/jq300/__init__.py#L107

I don't know about python @Limych but it seems for some reason, when starting, this is `NoneType`.
